### ISSUE TITLE
"received only 1 responses from 2 CL=QUORUM" query error having RF=3 and only 1 down node

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/gocql#101]
### What version of Scylla or Cassandra are you using?
4.6.3 , 2022.1.rc8

### What version of Gocql are you using?
1.6.0

### What version of Go are you using?
1.17.4

### What did you do?
Created 5-node Scylla cluster and ran `scylla-bench` tool that uses this `gocql` driver. Commands are following:
```
stress_cmd:                                                                                            
- scylla-bench -workload=sequential -mode=write -replication-factor=3 -partition-count=25 -clustering-row-count=10000 -partition-offset=401 -clustering-row-size=uniform:10..1024 -concurrency=10 -connection-count=10 -consistency-level=quorum -rows-per-request=10 -timeout=30s -retry-number=30 -retry-interval=80ms,1s -iterations 10
- scylla-bench -workload=sequential -mode=write -replication-factor=3 -partition-count=25 -clustering-row-count=100 -partition-offset=426 -clustering-row-size=uniform:2048..5120 -concurrency=10 -connection-count=10 -consistency-level=quorum -rows-per-request=10 -timeout=30s -retry-number=30 -retry-interval=80ms,1s -iterations 10
- scylla-bench -workload=sequential -mode=write -replication-factor=3 -partition-count=25 -clustering-row-count=10 -partition-offset=451 -clustering-row-size=uniform:5120..8192 -concurrency=10 -connection-count=10 -consistency-level=quorum -rows-per-request=10 -timeout=30s -retry-number=30 -retry-interval=80ms,1s -iterations 10
- scylla-bench -workload=sequential -mode=write -replication-factor=3 -partition-count=25 -clustering-row-count=1 -partition-offset=476 -clustering-row-size=uniform:8192..10240 -concurrency=10 -connection-count=10 -consistency-level=quorum -rows-per-request=10 -timeout=30s -retry-number=30 -retry-interval=80ms,1s -iterations 10
- scylla-bench -workload=sequential -mode=read  -replication-factor=3 -partition-count=25 -clustering-row-count=5555 -clustering-row-size=uniform:1024..2048 -concurrency=100 -connection-count=100 -consistency-level=quorum -rows-per-request=10 -timeout=30s -retry-number=30 -retry-interval=80ms,1s -iterations 0 -duration=170m -validate-data 
- scylla-bench -workload=sequential -mode=read  -replication-factor=3 -partition-count=25 -clustering-row-count=5555 -partition-offset=26 -clustering-row-size=uniform:1024..2048 -concurrency=100 -connection-count=100 -consistency-level=quorum -rows-per-request=10 -timeout=30s -retry-number=30 -retry-interval=80ms,1s -iterations 0 -duration=170m -validate-data
- scylla-bench -workload=sequential -mode=read  -replication-factor=3 -partition-count=25 -clustering-row-count=5555 -partition-offset=51 -clustering-row-size=uniform:1024..2048 -concurrency=100 -connection-count=100 -consistency-level=quorum -rows-per-request=10 -timeout=30s -retry-number=30 -retry-interval=80ms,1s -iterations 0 -duration=170m -validate-data
- scylla-bench -workload=sequential -mode=read  -replication-factor=3 -partition-count=25 -clustering-row-count=5555 -partition-offset=76 -clustering-row-size=uniform:1024..2048 -concurrency=100 -connection-count=100 -consistency-level=quorum -rows-per-request=10 -timeout=30s -retry-number=30 -retry-interval=80ms,1s -iterations 0 -duration=170m -validate-data
```

As it can be seen. We use `RF=3` and `CL=quorum`.
Then, as part of a test run we do various disruptions to Scylla cluster. ANd when we run `terminate and replace node` disruption/nemesis we get following error with pretty high probability:

```
Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
```

Host selection policy which we use is `token-aware` with fallback to `round-robin`. But, `host-pool` with automatic detection of down nodes behaves the same way.

Note that this problem is not rare it gets caught a lot of times. It is hard to not catch it making a Scylla node go down.

### What did you expect to see?
No errors because there must be 2 alive Scylla nodes holding replicas and only 1 down (expected).

### What did you see instead?
The mentioned error which assumes that one of the Scylla nodes that holds one of replicas is not contacted to.

### Logs

CI job: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/valerii/job/longevity-large-partition-asymmetric-cluster-3h/13/console
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/700cb0a5-d24d-43a1-b191-4cf8e954cffe/20220628_125019/db-cluster-700cb0a5.tar.gz
monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/700cb0a5-d24d-43a1-b191-4cf8e954cffe/20220628_125019/monitor-set-700cb0a5.tar.gz
loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/700cb0a5-d24d-43a1-b191-4cf8e954cffe/20220628_125019/loader-set-700cb0a5.tar.gz
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/700cb0a5-d24d-43a1-b191-4cf8e954cffe/20220628_125019/sct-runner-700cb0a5.tar.gz

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by martin-sucha** [comment]
Hello! This is an error from the Scylla server and not an error at gocql side. The Scylla server coordinator node could only get response from 1 replica. Is it possible that you overloaded the cluster by bringing one of the nodes down?

**Comment by vponomaryov** [comment]
> Hello! This is an error from the Scylla server and not an error at gocql side. The Scylla server coordinator node could only get response from 1 replica. Is it possible that you overloaded the cluster by bringing one of the nodes down?

No. The load was about 25%.
Proof:
![scylla-monitor-for-gocql-issue-101](https://user-images.githubusercontent.com/3796058/176932557-d377eff8-d053-4024-b85e-e92b6c4c15f2.png)

**Comment by fruch** [comment]
* we need to see if retries did work, and took into action, is there a way to enable debug to see that ?
* if all the timeout are in coordinator end and fail even when retried, so yes sound like a scylla end issue. (and we should move it there)

**Comment by vponomaryov** [comment]
> You can supply a [QueryObserver](https://pkg.go.dev/github.com/gocql/gocql#QueryObserver) and [BatchObserver](https://pkg.go.dev/github.com/gocql/gocql#BatchObserver) to count the number of query attempts. The occurrences with `Attempt > 0` are retries.

I implemented simple observe query logger and, looks like, it is useless for this case.

Here is how it looks like:
```
2022/07/15 18:08:15 [CQL] query: '''SELECT pk, ck, v FROM scylla_bench.test WHERE pk = ? AND ck >= ?  LIMIT 10 ''' is attempted 13 time
...
2022/07/15 18:08:15 [CQL] query: '''SELECT pk, ck, v FROM scylla_bench.test WHERE pk = ? AND ck >= ?  LIMIT 10 ''' is attempted 2879 time
2022/07/15 18:08:15 [CQL] query: '''SELECT pk, ck, v FROM scylla_bench.test WHERE pk = ? AND ck >= ?  LIMIT 10 ''' is attempted 2881 time
```
Here we can see that attempts just grow with the load alongside having completely healthy cluster.
So, it is not number retries made after failed attempts.

**Comment by martin-sucha** [comment]
How does the code executing the queries look like? It seems that the code might be calling Query.Exec multiple times with the same `*Query` value?

gocql currently has a note in the [documentation](https://pkg.go.dev/github.com/gocql/gocql#hdr-Executing_queries) that queries shouldn't be reused across multiple executions. This is one of the reasons why I added that note there. Historically it was not documented what the usage of Query should look like though, so it's possible that scylla-bench reuses the query.

**Comment by vponomaryov** [comment]
> How does the code executing the queries look like? It seems that the code might be calling Query.Exec multiple times with the same `*Query` value?
> 
> gocql currently has a note in the [documentation](https://pkg.go.dev/github.com/gocql/gocql#hdr-Executing_queries) that queries shouldn't be reused across multiple executions. This is one of the reasons why I added that note there. Historically it was not documented what the usage of Query should look like though, so it's possible that scylla-bench reuses the query.

The code just reads and logs, no calls at all.
And yes, I also think that `scylla-bench` uses same query all the time.

**Comment by vponomaryov** [comment]
@martin-sucha

For some reason, github doesn't allow me to add you as a reviewer to the fix of this bug here: https://github.com/scylladb/gocql/pull/104

**Comment by vponomaryov** [comment]
The problem was in the incorrect usage of the queries.
Closing because fix must be in the `scylla-bench` project.
