### ISSUE TITLE
gocql does not re-resolve DNS names (issue 831 from https://github.com/gocql/gocql/issues/831)

### ISSUE THREAD

**Issue by mykaul** [scylladb/gocql#118]
DNS remains the same, but IP changes for the control connection node. Need to understand the behavior when a node is replaced:

```[tasklist]
### Tasks
- [ ] The node is not the one the control connection is with.
- [ ] The node is *the* one the control connection is with.

```

**Comment by avelanarius** [comment]
Since https://github.com/gocql/gocql/commit/b9737ddcadbbe8092b27df4f6ab2e6e9f3cf4c72 was merged and we fetched it from the upstream, this can be closed.
