### ISSUE TITLE
Client is sending OPTIONS command to all shards in a node - while it should be sufficient to get it from a single shard

### ISSUE THREAD

**Issue by mykaul** [scylladb/gocql#129]
The response (SUPPORTED) will be the same from all shards - it's useless to send it to all shards and just an overhead to both sides.
(note: seen in a packet capture - unsure what driver was used, I suspect the GoCQL driver)

**Comment by mmatczuk** [comment]
Note that options frame is often used as L7 ping due to the lack of better alternatives.

**Comment by mykaul** [comment]
> Note that options frame is often used as L7 ping due to the lack of better alternatives.

Good to know! TCP keepalive (while not L7) seems sufficient to me though.

**Comment by mykaul** [comment]
Could it be that it needs it for SCYLLA_SHARD_AWARE_PORT information?

**Comment by mykaul** [comment]
https://github.com/scylladb/gocql/issues/162 is not fixing it, but making it less noisy.
