### ISSUE TITLE
session [goroutine / thread] safety

### ISSUE THREAD

**Issue by alidehghan** [scylladb/gocql#134]
is cluster.createSession is goroutine/thread safe (we can use one single instance in all routines) or it is better to create in any new go-routine?

what if connection drops and new routine needs to find (or reconnect to) new healthy node?

**Comment by sylwiaszunejko** [comment]
@alidehghan sorry for late reply
`cluster.createSession` function itself is not thead-safe operation that should be called concurrently from multiple goroutines. However, the session object created by this function is thread-safe and can be used safely across multiple goroutines. 

> what if connection drops and new routine needs to find (or reconnect to) new healthy node?

Do you mean all of the hosts are unreachable? Then the driver will try to reconnect. If you have some specific problematic scenario in mind please leave more details.

**Comment by sylwiaszunejko** [comment]
@alidehghan sorry for late reply
cluster.createSession function itself is thead-safe operation. Also, the session object created by this function is thread-safe and can be used safely across multiple goroutines.

>what if connection drops and new routine needs to find (or reconnect to) new healthy node?

Do you mean all of the hosts are unreachable? Then the driver will try to reconnect. If you have some specific problematic scenario in mind please leave more details.

**Comment by dkropachev** [comment]
> what if connection drops and new routine needs to find (or reconnect to) new healthy node?

The way `createSession` works is it creates a session, which is totally threadsafe and then initializes it, by establishing one control connection to the cluster, to get info on it's topology, which is not thread-safe, but given the fact that is process works on newly created session whole `createSession` is a thread safe, you can call in in parrallel as many times as you want. 

Before https://github.com/scylladb/gocql/pull/231, if session fails to connect to the cluster `createSession` would return an error, so you can handle it in our code and providing more nodes to the `ClusterConfig` and retry on `createSession` again. 
After https://github.com/scylladb/gocql/pull/231 `InitialReconnectionPolicy` controls this behavior, by default it does the same as before, but you can change policy and make it retry on error.

Either way if you want to update list of the nodes, you need to handle it in our app right after `createSession` fails.

**Comment by sylwiaszunejko** [comment]
As there is no further questions, I will close the issue. Please reopen if there are any concerns
