### ISSUE TITLE
Rebase to upstream 1.6.0

### ISSUE THREAD

**Issue by mykaul** [scylladb/gocql#143]
https://github.com/gocql/gocql/releases/tag/v1.6.0 was released and specifically has two important items:
- Added the com.scylladb.auth.SaslauthdAuthenticator and com.scylladb.auth.TransitionalAuthenticator
to the list of default approved authenticators. (https://github.com/gocql/gocql/pull/1712)
- Increased default timeouts so that they are higher than Cassandra default timeouts.
This should help prevent issues where a default configuration overloads a server using default timeouts
during retries. (https://github.com/gocql/gocql/issues/1701, https://github.com/gocql/gocql/pull/1719)

**Comment by martin-sucha** [comment]
For the record, `com.scylladb.auth.SaslauthdAuthenticator` and `com.scylladb.auth.TransitionalAuthenticator` are already present in scylladb/gocql since 428d676d679ca4390d86a15bac6c0315acf70f40.

**Comment by mykaul** [comment]
> For the record, `com.scylladb.auth.SaslauthdAuthenticator` and `com.scylladb.auth.TransitionalAuthenticator` are already present in scylladb/gocql since [428d676](https://github.com/scylladb/gocql/commit/428d676d679ca4390d86a15bac6c0315acf70f40).

Yes, but now I'm hoping less merge conflicts then ;-)
