### ISSUE TITLE
gocql: no hosts available in the pool" cannot recover without restart

### ISSUE THREAD

**Issue by maverick-ai** [scylladb/gocql#163]
We are using the latest docker of Scylla and running it as a single instance of Scylla inside docker container. We are using scylla version of gocql in our app. What we noticed is that after some days the driver disconnects from the database and it is not to reconnect connect to database. This is also an open issue in Gocql (https://github.com/gocql/gocql/issues/915). The only solution is to restart the application. This issue also propogates to Scylla version of gocql.

Gocql 1.13
Go 1.22.0

**Comment by mykaul** [comment]
Logs from both sides (driver and node) are critically needed to understand this issue.

**Comment by Rikkuru** [comment]
https://github.com/gocql/gocql/issues/915#issuecomment-2127111424

I had this probled and it turned out to be a config problem

**Comment by mykaul** [comment]
Thanks @Rikkuru - anything we should improve in our documentation? Closing this for the time being.

**Comment by Rikkuru** [comment]
> anything we should improve in our documentation?
No. Some kind of warning in lo  (without debug build) could have helped me to figure it out sooner in this case but I would let gocql maintainers decide if it is necessary.
