### ISSUE TITLE
It's impossible to implement a custom host selection policy

### ISSUE THREAD

**Issue by isburmistrov** [scylladb/gocql#167]
We wanted to implement our own host selection policy because the existing ones don't satisfy our requirements, and realised it's basically impossible.

The problem is with type [SelectedHost](https://github.com/scylladb/gocql/blob/3c32c6cd75e529433ed0885d8c04ec4c96cf22a9/policies.go#L324) that must be returned by [NextHost](https://github.com/scylladb/gocql/blob/3c32c6cd75e529433ed0885d8c04ec4c96cf22a9/policies.go#L346).

In SelectedHost, one of the methods return an unexposed interface: [link](https://github.com/scylladb/gocql/blob/3c32c6cd75e529433ed0885d8c04ec4c96cf22a9/policies.go#L326). It would have been solvable perhaps, if `token` didn't use itself in the type definition:

```
type token interface {
	fmt.Stringer
	Less(token) bool
}
```

Can we please fix this weird thing, effectively prohibiting a custom host selection policy seems like a weird limitation.

**Comment by sylwiaszunejko** [comment]
Closing as we have issue covering that https://github.com/scylladb/gocql/issues/183
