### ISSUE TITLE
Time type not working properly 

### ISSUE THREAD

**Issue by dahankzter** [scylladb/gocql#17]
See upstream issue https://github.com/gocql/gocql/issues/1284

We need to either integrate a fix or fix it here.

Upstream PR: https://github.com/gocql/gocql/pull/1283

**Comment by penberg** [comment]
This is fixed by https://github.com/scylladb/gocql/commit/aa13f581ce04d8b76e1ab21894a507ee5fc0bc9e, no?

**Comment by dahankzter** [comment]
Yes let's close it.
