### ISSUE TITLE
RFE: make ToCQL use server side DESCRIBE SCHEMA

### ISSUE THREAD

**Issue by Michal-Leszczynski** [scylladb/gocql#195]
Method `func (km *KeyspaceMetadata) ToCQL() (string, error)` is doing basically the same thing as `DESC SCHEMA` query, but on the driver side.
There is no need to do it on both server and driver side, especially that driver will be always lagging behind scylla releases.
For example, the server side `DESCRIBE SCHEMA WITH INTERNALS` is already printing CQL statements about dropped and re-added columns (this is important feature in terms of using those CQL schema for restore purposes), but it is missing from the driver method.

IMO this method should be deprecated or rewritten to use the server side `DESC SCHEMA` so that it is safer and easier to maintain.

**Comment by mykaul** [comment]
Will it work against all supported versions of Scylla? What about Cassandra?

**Comment by mykaul** [comment]
> Will it work against all supported versions of Scylla? What about Cassandra?

@dimakr?

**Comment by dkropachev** [comment]
@mykaul , greate question, i will give it a test and update you, one of the options we have is to fallback ot old logic if `DESCRIBE SCHEMA WITH INTERNALS` is not available

**Comment by dkropachev** [comment]
> @mykaul , greate question, i will give it a test and update you, one of the options we have is to fallback to old logic (logic we currently have) if `DESCRIBE SCHEMA WITH INTERNALS` is not available

It won't but we can fallback to old behavior, added logic to handle it to the PR
