### ISSUE TITLE
Initial connection vs. reconnections

### ISSUE THREAD

**Issue by knadh** [scylladb/gocql#230]
Hi there.

`gocql.NewSession()` returns an error if the target cluster is unreachable for any reason. However, if it succeeds and there is a disconnection or unavailability at a later point, `ReconnectInterval` and `ReconnectionPolicy` attempts reconnections in the background gracefully.

In production, this means that if the target cluster is unavailable for any reason during an app's boot, it will fail to start outright (unless it builds its own retry/reconnect abstractions). Post successful boot, any disconnections can be handled gracefully thanks to the reconnect behaviour. Is there any way to get around the initialization being a stop-the-world bottleneck? Can it not hook into the existing reconnect behaviour?

Thank you.

**Comment by sylwiaszunejko** [comment]
I've transferred it to the right repo

**Comment by mykaul** [comment]
> I've transferred it to the right repo

I wonder if it's not an issue we have in other drivers as well.

**Comment by dkropachev** [comment]
Reconnection policy is being introduced at #231, part regarging doing `Session.Init` later or in parallel is goign to be handled at https://github.com/scylladb/gocql/issues/234
