### ISSUE TITLE
Rollback trace end signature if needed

### ISSUE THREAD

**Issue by dkropachev** [scylladb/gocql#242]
It turns out that for `insert` `Done processing` does not show up in the `trace log`.

To address that we changed it to `preparing a result` in  https://github.com/scylladb/gocql/pull/241
If it is confirmed to be an scylla issue, let's rollback https://github.com/scylladb/gocql/pull/241 when it is merged.

**Comment by sylwiaszunejko** [comment]
For inserts it looks like that: "Done preparing on a local shard - preparing a result."

**Comment by sylwiaszunejko** [comment]
In https://github.com/scylladb/scylladb/blob/5c0f6d461321c4daa66bf3ff83543b9788c5ce72/transport/server.cc#L1045 you can see that for `cql_server::connection::process_prepare` the last activity in tracing looks like `Done preparing on a local shard - preparing a result.` and for others (`process_execute_internal`, `process_query_internal` and `process_batch_internal`) it is `Done processing - preparing a result`. I missed this when writing a condition. So it is non issue

**Comment by dkropachev** [comment]
> In https://github.com/scylladb/scylladb/blob/5c0f6d461321c4daa66bf3ff83543b9788c5ce72/transport/server.cc#L1045 you can see that for `cql_server::connection::process_prepare` the last activity in tracing looks like `Done preparing on a local shard - preparing a result.` and for others (`process_execute_internal`, `process_query_internal` and `process_batch_internal`) it is `Done processing - preparing a result`. I missed this when writing a condition. So it is non issue

Looking at [scylladb/scylla-cqlsh](https://github.com/scylladb/scylla-cqlsh):
[here](https://github.com/scylladb/scylla-cqlsh/blob/86a280a1a6c274c5266eaa69134c1af9574abcab/pylib/cqlshlib/tracing.py#L73-L75) and [here](https://github.com/scylladb/python-driver/blob/fab07e13f86b070c1012901b8cf5587ccb9701c3/cassandra/query.py#L1006-L1017)
I have figured that it is better to wait till `select duration from system_traces.sessions` is not nil.

**Comment by sylwiaszunejko** [comment]
> > In https://github.com/scylladb/scylladb/blob/5c0f6d461321c4daa66bf3ff83543b9788c5ce72/transport/server.cc#L1045 you can see that for `cql_server::connection::process_prepare` the last activity in tracing looks like `Done preparing on a local shard - preparing a result.` and for others (`process_execute_internal`, `process_query_internal` and `process_batch_internal`) it is `Done processing - preparing a result`. I missed this when writing a condition. So it is non issue
> 
> Looking at [scylladb/scylla-cqlsh](https://github.com/scylladb/scylla-cqlsh): [here](https://github.com/scylladb/scylla-cqlsh/blob/86a280a1a6c274c5266eaa69134c1af9574abcab/pylib/cqlshlib/tracing.py#L73-L75) and [here](https://github.com/scylladb/python-driver/blob/fab07e13f86b070c1012901b8cf5587ccb9701c3/cassandra/query.py#L1006-L1017) I have figured that it is better to wait till `select duration from system_traces.sessions` is not nil.

I am not sure about that, how should I scan the query to get nil, now with 
```
var (
		coordinator string
		duration    int
	)

	iter := t.session.control.query(`SELECT coordinator, duration
		FROM system_traces.sessions
		WHERE session_id = ?`, traceId)

	iter.Scan(&coordinator, &duration)
```
when the trace is not ready coordinator will be empty string and duration will be 0. But I am not sure if checking that is enough, sometime tracing looks like that:
```
Tracing session 9dfcdef0650d11efbf3d2ee5378096b2 (coordinator: , duration: 0s):
2024/08/28 07:17:43.135712: Checking bounds [shard 0] (source: 192.168.100.12, elapsed: 1)
2024/08/28 07:17:43.135713: Processing a statement [shard 0] (source: 192.168.100.12, elapsed: 2)
2024/08/28 07:17:43.135743: Creating read executor for token -7012643373428192421 with all: [192.168.100.12] targets: [192.168.100.12] repair decision: NONE [shard 0] (source: 192.168.100.12, elapsed: 32)
2024/08/28 07:17:43.135744: Creating never_speculating_read_executor - speculative retry is disabled or there are no extra replicas to speculate with [shard 0] (source: 192.168.100.12, elapsed: 33)
2024/08/28 07:17:43.135747: read_data: querying locally [shard 0] (source: 192.168.100.12, elapsed: 36)
2024/08/28 07:17:43.135752: Start querying singular range {{-7012643373428192421, pk{000400000032}}} [shard 0] (source: 192.168.100.12, elapsed: 41)
2024/08/28 07:17:43.135755: [reader concurrency semaphore user] admitted immediately [shard 0] (source: 192.168.100.12, elapsed: 44)
2024/08/28 07:17:43.13576: [reader concurrency semaphore user] executing read [shard 0] (source: 192.168.100.12, elapsed: 49)
2024/08/28 07:17:43.135772: Querying cache for range {{-7012643373428192421, pk{000400000032}}} and slice [(-inf, +inf)] [shard 0] (source: 192.168.100.12, elapsed: 61)
2024/08/28 07:17:43.135794: Page stats: 1 partition(s), 0 static row(s) (0 live, 0 dead), 1 clustering row(s) (1 live, 0 dead) and 0 range tombstone(s) [shard 0] (source: 192.168.100.12, elapsed: 83)
2024/08/28 07:17:43.135801: Querying is done [shard 0] (source: 192.168.100.12, elapsed: 90)
2024/08/28 07:17:43.135812: Done processing - preparing a result [shard 0] (source: 192.168.100.12, elapsed: 102)
```
so it is lacking coordinator info and duration is zero, but "Done processing - preparing a result" is there

**Comment by dkropachev** [comment]
> so it is lacking coordinator info and duration is zero, but "Done processing - preparing a result" is there

I got confused a bit, it should be nor `nil`, neither `0`.

**Comment by sylwiaszunejko** [comment]
> > so it is lacking coordinator info and duration is zero, but "Done processing - preparing a result" is there
> 
> I got confused a bit, it should be nor `nil`, neither `0`.

I am just guessing that duration info is filled after `Done processing - preparing a result` is written and we can have a situation when `Done processing - preparing a result` is written but duration is not filled yet

**Comment by dkropachev** [comment]
> > > so it is lacking coordinator info and duration is zero, but "Done processing - preparing a result" is there
> > 
> > 
> > I got confused a bit, it should be nor `nil`, neither `0`.
> 
> I am just guessing that duration info is filled after `Done processing - preparing a result` is written and we can have a situation when `Done processing - preparing a result` is written but duration is not filled yet

Looking at the core code I can tell that it is not the case, only problem that can potentially be is that duration in not set in some cases, say on exception.

**Comment by dkropachev** [comment]
> 
> regardless the reason should we just wait until duration is not zero and omit this weird case when it is zero but we have tracing activities available?

Yes, let's ommit it, untill we face an issue with it.
