### ISSUE TITLE
full scan operations time out

### ISSUE THREAD

**Issue by tarzanek** [scylladb/gocql#27]
Please answer these questions before submitting your issue. Thanks!

### What version of Scylla or Cassandra are you using?
3.x

### What version of Gocql are you using?
1.3.0-rc.1

### What did you do?

I'm trying to scan scylla table in efficient way based on this https://github.com/scylladb/scylla-code-samples/blob/master/efficient_full_table_scan_example_code/efficient_full_table_scan.go#L61
I'm testing a different parameters, but this particular test was made with 1 thread and 10000 ranges per thread. So the token range was divided by 10000.
When I was trying to use CL=QUORUM I got.
`Operation timed out for services_prod_us.device_signals - received only 1 responses from 2 CL=QUORUM. with query:SELECT version,device_id,signal_bucket FROM device_signals WHERE token(version,device_id,signal_bucket) >= ? AND token(version,device_id,signal_bucket) <= ?; and range &{-xxxxx -yyyyyyy}.`
With CL=LOCAL_ONE
`Operation timed out for services_prod_us.device_signals - received only 0 responses from 1 CL=LOCAL_ONE. with query:SELECT version,device_id,signal_bucket FROM device_signals WHERE token(version,device_id,signal_bucket) >= ? AND token(version,device_id,signal_bucket) <= ?; and range &{xxxxx  yyyyyyy}`
error type is `(*gocql.RequestErrReadTimeout)`
Scylla config
```
cluster := gocql.NewCluster(address...)
cluster.CQLVersion = "3.3.1"
cluster.NumConns = 16
cluster.ConnectTimeout = 10 * time.Second
cluster.Consistency = gocql.Quorum
cluster.DisableInitialHostLookup = disableInitHostLookup
cluster.Compressor = &gocql.SnappyCompressor{}
cluster.PoolConfig.HostSelectionPolicy =
gocql.TokenAwareHostPolicy(gocql.RoundRobinHostPolicy())
cluster.Timeout = 1 * time.Minute
cluster.RetryPolicy = &scylladb.MyExponentialBackoffRetryPolicy{NumRetries: 15, Min: 10 * time.Millisecond, Max: time.Minute}
```
MyExponentialBackoffRetryPolicy is the same as ExponentialBackoffRetryPolicy but I'm logging `Attempt` function call.

gocql: github.com/scylladb/gocql v1.3.0-rc.1

1. Why gocql.RequestErrReadTimeout is not triggering RetryPolicy? (Retry policy is working fine when the cluster.Timeout is exceeded and ErrTimeoutNoResponse is triggered.)
2. How to change timeout for `gocql.RequestErrReadTimeout` and what it means and what is the difference between `RequestErrReadTimeout` and `ErrTimeoutNoResponse`
3. How it's possible that I got this error with CL=LOCAL_ONE with `TokenAwareHostPolicy`?

### What did you expect to see?
No timeouts and if needed the retry policy should kick in

### What did you see instead?
time outs on some queries

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by tarzanek** [comment]
I think the problem is that you get timeouts Adam. The driver does not consider these to be retryable errors
I can get the retry policy to reconnect but once I get timeouts (surprisingly easy on a laptop) it stops promptly
The code also works much like this:
```
iter = q.attemptQuery(ctx, qry, conn)
iter.host = selectedHost.Info()
// Update host
switch iter.err {
    case context.Canceled, context.DeadlineExceeded, ErrNotFound:
        // those errors represents logical errors, they should not count
        // toward removing a node from the pool        
               selectedHost.Mark(nil)
               return iter
    default:
        selectedHost.Mark(iter.err)
}
```

**Comment by tarzanek** [comment]
RequestErrReadTimeout - This is probably server site timeout. And probably it’ catched by one of this context.Canceled, context.DeadlineExceeded, ErrNotFound because RetryPolicy is not call in this case

This is a direct error frame which comes from the server
It is parsed deep in the driver protocol parts as a correct response
but simply a timeout

is it intentional to don’t call retry policy in this case ?

In the case of regular deadlines yes but the one you get I need to checkout a little bit more
I want to clarify how exactly the reasoning goes for how this is handled 

But it clearly logs things like:
```
{"L":"INFO","T":"2019-10-08T09:33:01.934+0200","M":"ATTEMPT","num_retries":100,"retries":4,"_trace_id":"6LN8pO-URlyfrC3DF8MyYw"}
{"L":"INFO","T":"2019-10-08T09:33:02.079+0200","M":"ATTEMPT","num_retries":100,"retries":11,"_trace_id":"6LN8pO-URlyfrC3DF8MyYw"}
{"L":"INFO","T":"2019-10-08T09:33:02.079+0200","M":"ATTEMPT","num_retries":100,"retries":11,"_trace_id":"6LN8pO-URlyfrC3DF8MyYw"}
{"L":"INFO","T":"2019-10-08T09:33:02.688+0200","M":"ATTEMPT","num_retries":100,"retries":16,"_trace_id":"6LN8pO-URlyfrC3DF8MyYw"}
{"L":"INFO","T":"2019-10-08T09:33:02.691+0200","M":"ATTEMPT","num_retries":100,"retries":16,"_trace_id":"6LN8pO-URlyfrC3DF8MyYw"}
```
This is from the policy
If your policy Attempt is never called it means it exits earlier
The retries in the logs is from the query object that gets passed into the policy

So, the retry policy is also working for me if it’s a client site timeout. But not working if it’s RequestErrReadTimeout

And the problem is that I cannot reproduce this on my local machine. Even when I set read_request_timeout_in_ms to 100. Maybe I should change some order value in scylla.yaml ?


Actually I think it should be retried
If your policy always returns RetryNextHost it should retry
Are you sure the retry limit isn't reached?

Ok, I changed range_request_timeout_in_ms to 100 and the error appeared on my local Mac. And surprisingly the retry policy Attempt function was called.


Ah good catch
What is the range timeout in the real cluster? 
and read

range_request_timeout_in_ms is default, the row is scylla.yaml is commented out. Read timeout is 10s

**Comment by dahankzter** [comment]
Do you call `Release()` on the query objects at any point? It seems to be the only place where the metrics is reset thus allowing the retries to resume after once hitting the retry limit.

**Comment by dyasny** [comment]
@tarzanek what is the status here? Both ticket 862 and this issue are getting a bit stale...

**Comment by tarzanek** [comment]
Adam Sowinski 12:15 PM
Hi, I have more facts about efficient table scan.
1. I think, you have a bug in your version. I’m not an expert, and I didn’t have time to read entire gocql lib but it looks like this line https://github.com/scylladb/scylla-code-samples/blob/master/efficient_full_table_scan_example_code/efficient_full_table_scan.go#L235 should be inside the for loop below. In the other case, the auto paging doesn’t work.
2. I checked again on prod and retry policy attempt function is not called when this error appeared (*gocql.RequestErrReadTimeout) Operation timed out for services_prod_us.device_trips - received only 0 responses from 1 CL=LOCAL_ONE. with query:SELECT version,device_id,trip_bucket FROM device_trips WHERE token(version,device_id,trip_bucket) >= ? AND token(version,device_id,trip_bucket) <= ?; and range &{-9198930100957110588 -9198814808806649904}.
I’m testing now the version with auto paging and is seems to be better. Maybe reusing the prepared query was also a cause of timeout.

The first point is just a suggestion, I never run your code, so I’m not sure if i’m right. I found this bug in my code written based on yours, so I just wanted to draw your attention to this.
The ticket about the second one is already there, I just wanted to confirm, that it’s happened again.


Henrik 3:00 PM
Wow @Adam Sowinski that auto paging thing is new to me. Would you mind opening an issue for it? Does it happen on all sorts of queries that needs pagination?
Could it be that the page state isn't properly reset on bind?
Adam Sowinski 3:03 PM
this is what i suspect.
because it was working fine when I paginated  by myself.
Henrik 3:04 PM
That's my guess without having tried it
A fix should be trivial but a test case is needed in the suite so it doesn't get lost in the future
Rafal 3:05 PM
https://github.com/gocql/gocql/blob/master/cassandra_test.go#L2598 it looks like only PageState(nil) disables autopaging
cassandra_test.go:2598
    query := session.Query("SELECT id, count FROM testManualPaging").PageState(nil).PageSize(2)
<https://github.com/gocql/gocql|gocql/gocql>gocql/gocql | Added by GitHub
Adam Sowinski 3:05 PM
yes
Henrik 3:07 PM
Yes @Rafal a non existent pagestate makes it unpaginated but now we have a page state on the query from the previous Bind.... I think at least which seems really bad
Adam Sowinski 3:11 PM
So my guess is that we have something more than page state there. Maybe some timeouts or something what is a cause on the timeout error or not calling retry policy.
But i didn’t dig that deep.
Henrik 3:26 PM
Are they related? I think it's a separate issue with the paging
Maybe they play together as well
Henrik 3:38 PM
The paging problem was easily reproducible
Ill clean up the test and send an upstream patch

Henrik 9:55 AM
I just released 1.3.0 @Adam Sowinski with the fix for the paging as well as the fixes in the RC (edited) 
:scylla:
1

tomersan:scylla: 8:40 PM
Hi @Adam Sowinski when you get to using the newly released scylladb/gocql - let us know if that helped, Thanks!
Adam Sowinski 7:59 PM
@tomersan @Henrik thx. It’s helping with auto paging but the timeout problem is still there. What can we do with this problem ?
Henrik 8:20 AM
I still haven't been able to reproduce it. Could you describe some more about your schema and the queries that fail @Adam Sowinski? RF in particular and cluster size.

**Comment by tarzanek** [comment]
Adam Sowinski 12:13 PM
I don’t think it is a bug. The only thing which could be a bug is a retry policy call. But like I said it’s working fine on my local machine. And I cannot reproduce this bug on prod anymore to check again if retry policy i called there.

**Comment by yksdb** [comment]
Original helpdesk ticket 862 was closed in Dec 2019. @tarzanek if no dependencies to other issues please close this issue too.
