### ISSUE TITLE
unmarshall `nil` and `zero` `decimal` into `inf.Dec` unsupported 

### ISSUE THREAD

**Issue by illia-li** [scylladb/gocql#282]
Currently if we try unmarshalls `decimal` with `nil` and `zero` `value` into `inf.Dec` - the `unmarshall` function return an error: `inf.Dec needs at least 4 bytes, while value has only 0`
According to `cql` protocol -  for all `types` value can be `nil` and `zero`.
Therefore `unmarshall` function should support unmarshalls `nil` and `zero` value  for all `types`.

**Comment by dkropachev** [comment]
@illia-li , is this solved ?

**Comment by illia-li** [comment]
> [@illia-li](https://github.com/illia-li) , is this solved ?

Yeap. I forgot to mention this in the PR #367
