### ISSUE TITLE
Index out of bounds when getting db conn

### ISSUE THREAD

**Issue by cbass561** [scylladb/gocql#29]
### What version of Scylla or Cassandra are you using?
3.0.2

### What version of Gocql are you using?
1.3.1

### What did you do?
Server was running for several days (10+) and a query was executed

### What did you expect to see?
The query to execute correctly

### What did you see instead?
A panic when the internal gocql client attempted to establish a connection to the db. The exact error was:

`github.com/gocql/gocql.(*Session).executeQuery(0xc002f13500, 0xc005b12a20, 0x12eef5e)
goroutine 100090784 [running]:
github.com/gocql/gocql.(*scyllaConnPicker).randomConn(0xc0001026e0, 0xc003f95538)
	/go/pkg/mod/github.com/scylladb/gocql@v1.3.1/scylla.go:236 +0x83
github.com/gocql/gocql.(*scyllaConnPicker).Pick(0xc0001026e0, 0x0, 0x0, 0xc000699740)
	/go/pkg/mod/github.com/scylladb/gocql@v1.3.1/scylla.go:152 +0x100
github.com/gocql/gocql.(*hostConnPool).Pick(0xc0006691f0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/scylladb/gocql@v1.3.1/connectionpool.go:313 +0xd9
github.com/gocql/gocql.(*queryExecutor).do(0xc0056757a0, 0x14c34c0, 0xc00003e0e0, 0x14d3560, 0xc005b12a20, 0x20300f)
	/go/pkg/mod/github.com/scylladb/gocql@v1.3.1/query_executor.go:106 +0x18c
github.com/gocql/gocql.(*queryExecutor).executeQuery(0xc0056757a0, 0x14d3560, 0xc005b12a20, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/scylladb/gocql@v1.3.1/query_executor.go:60 +0x437
panic: runtime error: index out of range [-32]
	/go/pkg/mod/github.com/scylladb/gocql@v1.3.1/session.go:431 +0xb7
github.com/gocql/gocql.(*Query).Iter(0xc005b12a20, 0xc005b12a20)
	/go/pkg/mod/github.com/scylladb/gocql@v1.3.1/session.go:1135 +0xa5
github.com/gocql/gocql.(*Query).Exec(0xc005b12a20, 0xc00ad2d000, 0x7b)
	/go/pkg/mod/github.com/scylladb/gocql@v1.3.1/session.go:1118 +0x2b`

I believe the issue lies in the scyllaConnPicker.randomConn() method. 

`func (p *scyllaConnPicker) randomConn() *Conn {
  idx := int(atomic.AddInt32(&p.pos, 1))
  for i := 0; i < len(p.conns); i++ {
    if conn := p.conns[(idx+i)%len(p.conns)]; conn != nil {
      return conn
    }
  }
  return nil
}`
For long running processes, idx will eventually overflow and cause a panic when attempting to select a connection. It should be changed (I can change it too) to circle back to zero when number overflows.

**Comment by dahankzter** [comment]
Interesting! I will take a look at asap. It would be good with a reproducible example if you have a small case.

**Comment by mmatczuk** [comment]
Fixed with #31

**Comment by dahankzter** [comment]
This was fixed y you already @cbass561 :) thx!
