### ISSUE TITLE
Query retry logic is not triggered in certain cases

### ISSUE THREAD

**Issue by dkropachev** [scylladb/gocql#326]
Query executor does not involve retry policy in certain cases
https://github.com/scylladb/gocql/blob/fc1b783165b9629112d226580e2edafbc3c30f49/query_executor.go#L109-L198

These cases are 
1. Host is down
2. Host does not have pool
3. Host pool does not have connections

Probably it make sense to involve retry policy in such cases.
It will require policies to be smarter in regards of the `GetRetryType` results, in listed cases.
Also it will break API a bit in a sense that we will have to introduce new errors which will be returned instead of `ErrNoConnections`

**Comment by sylwiaszunejko** [comment]
@dkropachev Currently in these cases you mentioned we don't use retry policy, but we retry on the next host always. It is true even if retry policy is not defined. I am not sure what correct behavior should be if one of those cases occur: 
> 1. Host is down
> 2. Host does not have pool 
> 3. Host pool does not have connections
and `rt == nil`, should we then stick to the current behavior and retry on the next host or should we just exit?

**Comment by sylwiaszunejko** [comment]
@dkropachev ping

**Comment by pdbossman** [comment]
I would think stopping the retry on next host would be a regression.  It seems to me - the request was not really tried.

**Comment by sylwiaszunejko** [comment]
> I would think stopping the retry on next host would be a regression. It seems to me - the request was not really tried.

Ok, so I guess if retry policy is not there we should retry on next host in those cases. Also I think the retry policies should be edited to make sure they always result in retry on next host for given scenarios
