### ISSUE TITLE
Idempotent flag ignored for retries

### ISSUE THREAD

**Issue by pdbossman** [scylladb/gocql#331]
Hello,
I was testing goCQL behavior with request shedding enabled.  So I set
`max_concurrent_requests_per_shard: 10`

I was testing vanilla insert with value clause.

Initially, requestRetryPolicy was disabled, and I received shedding errors.

I then enabled requestRetryPolicy with ExponentialBackoffRetryPolicy.
```
    requestRetryPolicy := &gocql.ExponentialBackoffRetryPolicy{
		Min:        100 * time.Millisecond,  // Minimum retry delay
        //Min:        time.Second,  // Minimum retry delay
        Max:        10 * time.Second, // Maximum retry delay
        NumRetries: 10,           // Maximum number of retries
    }
```

As expected, queries were retried.  I still observed shedding in monitoring, but the driver retried the requests with exponential backoff.

I then tested with idempotent set to false.
```
func insertQuery(session *gocql.Session, ctx context.Context, firstName, lastName, address, pictureLocation string, increment int, logger *zap.Logger) bool {
	//sp := &gocql.SimpleSpeculativeExecution{NumAttempts: 2, TimeoutDelay: 1 * time.Millisecond}
	query := session.Query("INSERT INTO mutant_data (first_name,last_name,address,picture_location) VALUES (?,?,?,?)", firstName, lastName, address, pictureLocation)
	//query.SetSpeculativeExecutionPolicy(sp)
	query.Idempotent(false)
	if err := query.Exec(); err != nil {
		logger.Error("insert mutant_data "+firstName+" "+lastName, zap.Error(err))
	}
}
```

Problem: Even with Idemotent false, which should block retry - the queries were still retried with exponential backoff policy.  It also looks like it might be in general for all retries (speculative and timeout):
https://github.com/apache/cassandra-gocql-driver/pull/1809/commits/92b4056c1a125e7094b397cfab8bd8ac8d48f26e

All retry policies should honor the idempotent flag.

**Comment by mykaul** [comment]
> I don't have permissions to scylla-go-driver do I cannot transfer the issue

Done!

**Comment by dkropachev** [comment]
Fixed by https://github.com/scylladb/gocql/pull/376
