### ISSUE TITLE
Have unit tests for zero-token code

### ISSUE THREAD

**Issue by dkropachev** [scylladb/gocql#338]
1. We need move `getSchemaAgreement` to a separate function, arguments would be `c.query(ctx, localSchemas)`, `c.querySystemPeers(ctx, c.host.version)`, `c.host.ConnectAddress()`, `c.session.cfg.Port` and `c.session.cfg.translateAddressPort`, and have it unittested against zero-token case  https://github.com/scylladb/gocql/blob/1e181f35b5e6ab4051a5199e9c1796bb4c34d9d6/conn.go#L1843-L1894
2. Make `ringDescriber` testable and have unit tests for zero-token cases for `ringDescriber.GetHosts()` and `ringDescriber.getClusterPeerInfo`

**Comment by sylwiaszunejko** [comment]
@dkropachev Do I understand correctly that something like that should be function definition for 1. `func getSchemaAgreement(queryLocalSchemasRes *Iter, querySystemPeersRes *Iter, connectAddress net.IP, port int, translateAddressPort func(addr net.IP, port int) (net.IP, int), logger StdLogger) (err error) {
`
Or should I have the result of e.g. Iter.SliceMap() as a first two arguments?

**Comment by dkropachev** [comment]
> [@dkropachev](https://github.com/dkropachev) Do I understand correctly that something like that should be function definition for 1. `func getSchemaAgreement(queryLocalSchemasRes *Iter, querySystemPeersRes *Iter, connectAddress net.IP, port int, translateAddressPort func(addr net.IP, port int) (net.IP, int), logger StdLogger) (err error) { ` Or should I have the result of e.g. Iter.SliceMap() as a first two arguments?

Well, it depends on you, I personally would do that with iters, but if you have another approach that is better go ahead with it.

**Comment by sylwiaszunejko** [comment]
Partially fixed with: #347 and #349 

Still todo: have a way to test `ringDescriber.GetHosts()`. I am not sure how to do that, I could create separate function that takes localHost and peers information and returns all non zero-token hosts, but only thing it would do is check if localHost is zero-token and I am not sure it makes much sense.

**Comment by sylwiaszunejko** [comment]
@dkropachev Do we need any other tests except one added in #368
