### ISSUE TITLE
code in directory .../scylladb/gocql expects import "github.com/gocql/gocql"

### ISSUE THREAD

**Issue by dyasny** [scylladb/gocql#35]
Please answer these questions before submitting your issue. Thanks!

```
go version
go version go1.13.6 linux/amd64
```

### What did you do?

```
go get github.com/scylladb/gocql
package github.com/scylladb/gocql: code in directory /home/dyasny/go/src/github.com/scylladb/gocql expects import "github.com/gocql/gocql"
```

### What did you expect to see?

a module installed with no errors

**Comment by dahankzter** [comment]
This is not really the preferred way to work with the library. The idea is to work with the original code and imports then change implementation by using a replace directive in the `go.mod` file. I think this is stated in the readme but perhaps we can make it more clear.
