### ISSUE TITLE
Make driver invalidate tablets

### ISSUE THREAD

**Issue by dkropachev** [scylladb/gocql#350]
## Invalidation on events
- On `SCHEMA_CHANGE`, for target `keyspace` + `table`, for all change types: `UPDATED` or `DROPPED` drop related tablet records. 
- On `TOPOLOGY_CHANGE`, for `REMOVED_NODE` ~~(and probably `MOVED_NODE`)~~ change type, all tablet records that contains this node, to be removed.

Possible optimizations:
- On `SCHEMA_CHANGE` change types: `UPDATED` driver can look at what have changed and if nothing that can trigger tablet migration (say, ks replication factor and tablet feature on the table) is touched, then invalidation to be voided 

## Invalidation on control connection reconnect
When cc is lost, driver can miss some of the events.
So we need some logic to catch up:
- Read keyspace and table descriptions to find if any keyspace or table was removed or updated, doing exactly the same what should be done for `SCHEMA_CHANGE` event.
- Read `system.peers` to find if any node was removed and do the same what should be done for `TOPOLOGY_CHANGE` event.

**Comment by dkropachev** [comment]
https://github.com/scylladb/gocql/pull/351 does not fix all of it

**Comment by sylwiaszunejko** [comment]
https://github.com/scylladb/gocql/pull/351#issuecomment-2498144809 @dkropachev could you please answer my question from that comment? I would like to make sure the next steps with this issue are clear

**Comment by dkropachev** [comment]
> [#351 (comment)](https://github.com/scylladb/gocql/pull/351#issuecomment-2498144809) [@dkropachev](https://github.com/dkropachev) could you please answer my question from that comment? I would like to make sure the next steps with this issue are clear

First of, we want to see of keyspace had changed correct ?
Which means that we will need to keep old metadata intact while we doing that.
Same goes for hosts and tables.

**Comment by sylwiaszunejko** [comment]
@dkropachev Is there anything more I should do with this issue? Should I implement:

> Possible optimizations:
>
>  *  On SCHEMA_CHANGE change types: UPDATED driver can look at what have changed and if nothing that can trigger tablet migration (say, ks replication factor and tablet feature on the table) is touched, then invalidation to be voided

It would require some changes to the logic, because normally on event we don't fetch new schema only clear the old one and fetch new when it is needed

**Comment by dkropachev** [comment]
Let's dont' do that.
