### ISSUE TITLE
Split Conn.querySystemPeers

### ISSUE THREAD

**Issue by dkropachev** [scylladb/gocql#365]
In order to make internals testable we need to split to code from `Conn.querySystemPeers` into query execution and decision on what to execute, at the end we should end up with:
1. `isSchemaV2` flag on `Conn` that is initiated on Conn during `Conn.init`: 
Right now `isSchemaV2` is set in `querySystemPeers`, let's move it to init and do it once.
Please check that `init()` is called on `reconnect`, to ensure that when/if node is updated, driver rereads it as well.
2. Function `Conn.querySystem`()  that `Conn.session.usingTimeoutClause` into consideration when executes a query.
3. Standalone function that takes `Conn` (as interface) and returns same result as querySystemPeers

**Comment by sylwiaszunejko** [comment]
@dkropachev I believe it was fixed with #368
