### ISSUE TITLE
Prefer primary replica for the token for LWT queries

### ISSUE THREAD

**Issue by kostja** [scylladb/gocql#40]
The way Paxos protocol works is that if two queries attempt to update the same key from different coordinators, they will start two independent Paxos rounds. Each round will be assigned a timestamp, and the coordinator who has the highest timestamp will win. 
The issue is, the loser only queues up after the winner (using a semaphore) if both rounds are coordinated by the same node. If rounds are started at different nodes, the only option for the user is to sleep increasingly random interval and retry (this is what our implementation does).

If the key is contended and the driver is neither shard nor token aware, this leads to a lot of retries to make an update than necessary. If the driver is token or shard aware, it will send the query to one of the replicas for the partition, but will use round-robin. 
This still means there will be at least 50% of loser queries, which will retry before they can commit.

This is why for LWT queries the driver should choose replicas in a pre-defined order, so that in case of contention they will queue up at the replica, rather than compete: choose the primary replica first, then, if the primary is known to be down, the first secondary, then the second secondary, and so on.
This will reduce contention over hot keys and thus increase LWT performance.

**Comment by mmatczuk** [comment]
Design proposal:

* Add `lwt bool` to Query, based on string search, they already do a similar thing in `shouldPrepare` func
* Add `IsLWT()` to `ExecutableQuery interface`
* Use this info in Pick function

**Comment by dahankzter** [comment]
The token aware driver already picks hosts according to the token ring sorted order regardless of the query type like this:
```
Replica_A: {"00", "10", "20"}
Replica_B: {"00", "10", "20"}
Replica_C: {"30", "40", "50"}
```
For token "12" it will start with the first local host that is known to be up say A and then proceed with B and then C. In case of token 35 it will start with C then proceed with A then B.
That is correct from LWT point of view already right @kostja or did I misunderstand?

**Comment by kostja** [comment]
Yes, this is exactly what LWT needs. But will it preserve this replica selection policy in all circumstances? E.g. Java driver round-robins between the primary and secondaries, will go driver do that?

**Comment by dahankzter** [comment]
I need to verify it but I think that it will consistently start from the first primary replicas and if all are down then it will try the secondary replicas.

This gives consistency in picking replica but I guess the chosen primary replica could suffer if it is very hot. Maybe not a problem since the problem could be worse if picking a random replica.

**Comment by mmatczuk** [comment]
@dahankzter this is not enought

1. We select replicas in a local DC only this does not have to be the **Primary Replica in a multi DC setting**.
1.There is a config option to shuffle replicas it should be disabled for LWT.

**Comment by dahankzter** [comment]
Are you sure @mmatczuk? There is a config option `NonLocalReplicasFallback()` that controls this afaict. We can easily ignore the shuffling by using the approach you outlined but only for LWT queries I think. There may be a reason for the user to shuffle other queries.

**Comment by kostja** [comment]
I have not provided guidance for multi-DC setup. If LOCAL_SERIAL serial consistency is used, we should prefer the primary in the local DC. If SERIAL consistency is specified, we should use any DCs primary, but consistently. The key to avoiding contention is in all clients consistently choosing the same replica for the same key, if it's available/alive.

**Comment by mmatczuk** [comment]
Thanks for update @kostja. Note that there is one "Primary replica" for a given token in a ring. There is no such thing as primary replica in DC X, there are however the 1st, 2nd and so on replicas in DC X, in some cases 1st replica in DC X will indeed be the "primary" but it does not have to be like that.

I'd like to clarify the replica fallback order.

Given DC A {N0, N1, N2} (local) and B {N3, N4, N5} with RF=2
Given a token with the following endpoints N0, N1, N3, N4.

When consistency is LOCAL_SERIAL we iterate over N0, N1.
When consistency is SERIAL we iterate over N3, N4.

Is that correct?

**Comment by dahankzter** [comment]
This will require changes to the way we select hosts but perhaps not too much.

Can we define what we actually mean by "primary replica"? A token is owned by a number of replicas how is any one of them actually "primary"?

**Comment by dahankzter** [comment]
So picking the primary replica in a remote DC is better than just exhausting the local replicas first @kostja? Perhaps the algorithm doesn't work unless primaries are used?

**Comment by kostja** [comment]
Cassandra issue: https://issues.apache.org/jira/browse/CASSANDRA-15746
