### ISSUE TITLE
It is impossible to read with LWT

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/gocql#58]
Consistency type does not contain SERIAL and LOCAL_SERIAL values so it is impossible to set consistency to be serial on read.

**Comment by kostja** [comment]
This is affecting temporal.io

**Comment by mmatczuk** [comment]
The driver supports [serial_consistency flag](https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v4.spec#L339) for updates.

> That consitency can only be either SERIAL or LOCAL_SERIAL and if not present, it defaults to SERIAL. 
> This option will be ignored for anything else other than a conditional update/insert.

At the same time [consistency](https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v4.spec#L227) enum has all values in the range 0x0 to 0xA containing SERIAL and LOCAL_SERIAL. That is not reflected by Consistency enum in the driver.

For current deployments the workaround could be casting ints to Consistency ex.

```
	// in TestQueryBasicAPI where qry := &Query{}

	qry.Consistency(Consistency(0x9))
	if qry.GetConsistency() != 0x9 {
		t.Fatalf("expected Query.GetConsistency to return 'LocalSerial', got '%s'", qry.GetConsistency())
	}
```

**Comment by mmatczuk** [comment]
@gleb-cloudius @kostja 1.4.3 is released now with a patch.

**Comment by kostja** [comment]
@mmatczuk are the changes made addressed in the documentation? The docs are  silent on how to read with Serial consistency.

**Comment by kostja** [comment]
@mmatczuk ping re updating the documentation. Would you like me to send a patch?

**Comment by mmatczuk** [comment]
Hey @kostja feel free to suggest something.
Maybe we can put it to https://pkg.go.dev/github.com/gocql/gocql#Query.SetConsistency
There are no real user docs here.

**Comment by martin-sucha** [comment]
Yeah, Query.SetConsistency is good place to put those docs in.

If you want to add something to package-level documentation I can merge https://github.com/gocql/gocql/pull/1513 upstream first (I can do the merge, but would prefer someone else to review it first as I have authored that pull request) and you could base your changes on top of that so that we don't create conflicts unnecessarily.

**Comment by dorlaor** [comment]
It will be great to merge/rebase (in general)
