### ISSUE TITLE
Cannot install the library

### ISSUE THREAD

**Issue by dogenkigen** [scylladb/gocql#66]
Please answer these questions before submitting your issue. Thanks!

### What version of Scylla or Cassandra are you using?
N/A

### What version of Gocql are you using?
latest

### What did you do?
I was trying to install the library by following the README. I feel like the instruction is a bit vague. I already had gocql/gocql installed on my machine. Now I wanted to switch to scylladb/gocql. It is impossible to to run command `go get github.com/scylladb/gocql` because it will result with an output like this:
```
go: github.com/scylladb/gocql upgrade => v1.4.3
go get: github.com/scylladb/gocql@v1.4.3: parsing go.mod:
	module declares its path as: github.com/gocql/gocql
	        but was required as: github.com/scylladb/gocql
```
I decided to clone the repository and run following command inside:
```
go mod edit -replace=github.com/gocql/gocql=github.com/scylladb/gocql@v0.0.0-20201029170107-81a4afe636ae01c9826794e83365a0023692303d
```
 The command returned without error but now when I want to use the library I get the error:
```
go: github.com/gocql/gocql@v0.0.0-20201029170107-81a4afe636ae01c9826794e83365a0023692303d: invalid version: unknown revision 81a4afe636ae01c9826794e83365a0023692303d
```

### What did you expect to see?
I expected the library to have some explanation in README how to use it

### What did you see instead?
Fail after following instructions

**Comment by mmatczuk** [comment]
The way to do that is with replace https://github.com/scylladb/gocql#installation

Example

```
require (
	github.com/gocql/gocql v0.0.0-20200131111108-92af2e088537
)
replace (
	github.com/gocql/gocql => github.com/scylladb/gocql v1.4.3
)
```

**Comment by dogenkigen** [comment]
Thanks, that worked! Have you considered adding that to the documentation?

**Comment by mmatczuk** [comment]
Where do you suggest to put it?

**Comment by avelanarius** [comment]
The information is now in https://github.com/scylladb/gocql?tab=readme-ov-file#installation, so closing this issue.
