### ISSUE TITLE
Write shard-aware ports blog post

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/gocql#67]
As a followup to https://github.com/scylladb/gocql/pull/52 we need to write a blog post introducing the feature.

It should contain:
* a description of how it works
* proof of usefulness - benchmark where many clients try to open connections so that we can show that before we opened X connections per shard now it's 1 flat

**Comment by mmatczuk** [comment]
cc @haaawk

**Comment by haaawk** [comment]
Unfortunately, @piodul has more urgent work to do.
I think a single blogpost for all the drivers will make more sense.

**Comment by haaawk** [comment]
Maybe @sitano would have time to look at this?

**Comment by sitano** [comment]
@haaawk I will ask my coordinator.

**Comment by tzach** [comment]
references:
https://www.scylladb.com/2020/10/13/making-a-shard-aware-python-driver-for-scylla-part-1/
https://www.scylladb.com/2020/10/15/making-a-shard-aware-python-driver-for-scylla-part-2/
https://www.slideshare.net/ScyllaDB/scylla-summit-2018-scylla-feature-talks-gains-by-using-scyllaspecific-drivers

**Comment by mmatczuk** [comment]
Note that here it's about shard aware ports.

**Comment by piodul** [comment]
A blog post about the shard-aware port feature was published yesterday. It describes how it works and shows that much less connection attempts are needed to establish connection per shard.

Link: https://www.scylladb.com/2021/04/27/connect-faster-to-scylla-with-a-shard-aware-port/
