### ISSUE TITLE
Question on bulk queries

### ISSUE THREAD

**Issue by vikmik** [scylladb/gocql#75]
Hello!

(not sure if this is the right place to ask questions - feel free to close if not)
Going over some online resources on Scylla performance, there's a recurring theme, which is:
* it _may_ be beneficial to do bulk queries (using `SELECT ... IN` on reads and `BATCH` on writes) instead of doing more parallel queries.
* when doing bulk queries, it is better to avoid requiring coordination across multiple nodes (= avoid bulk queries that require data from different nodes)

Example resources that touch on this:
* On `SELECT ... IN` queries: https://www.scylladb.com/tech-talk/planning-queries-maximum-performance-scylla-summit-2017/  (a bit old, but I think it is still relevant?)
* On `BATCH` insert queries: https://www.scylladb.com/2019/03/27/best-practices-for-scylla-applications/

Now, the application I'm working on needs to do large bulk reads and writes, so I want to make sure I'm not adding artificial bottlenecks.

With that in mind, I'm a bit puzzled about how to implement the above recommendations with `gocql`. Ideally the driver would let me split my bulk queries by node, but there does not seem to be a way to do so (?)
It seems the closest I can do using `gocql` is to have my application split bulk queries by partition key. But if I'm trying to read, let's say, 200K rows with all different partition keys, this basically means bulk queries will all be split into 200K single-row queries - which basically means I can't use bulk queries in practice - which _may_ be detrimental to my application performance.

Given that the driver has access to the information that would be required to split queries intelligently, I was wondering why there is no such facility? I'm not sure whether I am misunderstanding how to best use the driver, or if the driver is currently lacking the feature. It would surely require the driver to expose a rather odd-looking API (as the current gocql API seems pretty abstracted away from such concerns) - but that seems required in order to make bulk queries as efficient as they can be.

I'm completely new to the Scylla ecosystem so apologies if my question seems odd. Advice welcome, and sorry if I missed something obvious :)

Thanks!

**Comment by martin-sucha** [comment]
Yep, I'm not aware of any public API to determine which node (resp. in case of Scylla you would group by shard) the partition key maps to.

We just split our queries by partition key, although in our case we don't need to read 200K specific partition keys at once and we read more than one row from partition.

One advantage of splitting by partition key is that each partition can return error separately (e.g. in case some partition takes long to process, but that might be irrelevant if you only have one row per partition).

It would definitely be interesting to see a benchmark comparing the options.

**Comment by Codebreaker101** [comment]
I too would like to have the ability to batch my data according to which node/shard my data is going. Any new information regarding this?

**Comment by moguchev** [comment]
The same problem. I extend gocql driver with this function, which helps me to split keys into shard aware batches.
May be it would be helpful

```go
type ShardAwareRoutingInfo struct {
	// RoutingKey - is bytes of primary key
	RoutingKey []byte
	// Host - is node to connect
	Host *HostInfo
	// Shard - is shard ID of node to connect
	Shard int
}

// GetShardAwareRoutingInfo - определения ноды/шарда по PK ключу.
// Драйвер может не всегда получить информацию о маршрутизации и это нормально.
// В этом случае функция вернет ошибку и в вашем приложении требуется обработать ее штатно
//
// Пример использования для SELECT WHERE IN:
/*
	const shardsAbout = 100 // число node * (cpu-1)

	// Разбиваем []T на батчи (pk ключи)
	var (
		queryBatches = make(map[string][]T, shardsAbout) // сгруппированные ключи по батчам
		routingKeys  = make(map[string][]byte, shardsAbout) // routing key для маршрутизации запроса
	)

	for _, pk := range pks {
		var (
			shardID string
			routingKey []byte
		)
		// Получаем информацию о маршрутизации наших ключе.
		// В данном примере PRIMARY KEY состоит из одной колонки pk_column_name.
		info, err := session.GetShardAwareRoutingInfo(keyspaceName, tableName, []string{"pk_column_name"}, pk)
		if err != nil || info.Host == nil {
			// Мы можем не получить информацию о маршрутизации по разным причинам.
			// Важно при тестировании понять причину (например, вы не используете tokenAwarePolicy)
			log.Printf("can't get shard id of pk '%d': %v", pk, err)
		} else {
			// формурум уникальный ключ шарда: host+/+vShard (127.0.0.1/1)
			shardID = info.Host.Hostname() + "/" + strconv.Itoa(info.Shard)
			routingKey = info.RoutingKe
		}

		// добавляем наш ключ в соответсвующий батч
		batch := queryBatches[shardID]
		if batch == nil {
			batch = make([]int64, 0, len(pks)/shardsAbout)
		}
		batch = append(batch, pk)

		queryBatches[shardID] = batch
		routingKeys[shardID] = rk
	}

	const query = "SELECT * FROM table_name WHERE pk IN (?)"

	var wg sync.WaitGroup
	// пробегаемся по всем батчам для параллельного выполнения запросов
	for shard, batch := range batches {
		// большие батчи разделяем на чанки поменьше, так как большие батчи плохо влияют на RT scylla)
		for _, chunk := range slices.ChunkSlice(batch, 10) { // разделяем
			wg.Add(1)
			go func(shard string, chunk []int64) {
				defer wg.Done()

				rk := keys[shard] // достаем наш ключ маршрутизаци

				scanner := r.session.Query(query, chunk).RoutingKey(rk).Iter().Scanner() // используем RoutingKey

				for scanner.Next() {
					// ...
				}

				if err := scanner.Err(); err != nil {
					// ...
				}
			}(shard, chunk)
		}
	}
	// ждем отработки всех запросов
	wg.Wait()
*/
func (s *Session) GetShardAwareRoutingInfo(table string, primaryKeyColumnNames []string, args ...interface{}) (ShardAwareRoutingInfo, error) {
	keyspace := s.cfg.Keyspace

	// fail fast
	if len(keyspace) == 0 || len(table) == 0 {
		return ShardAwareRoutingInfo{}, errors.New("missing keyspace or table")
	}

	if len(primaryKeyColumnNames) == 0 {
		// missing a routing key column
		// no routing key
		return ShardAwareRoutingInfo{}, errors.New("missing a routing key column")
	}

	// check policy is TokenAwareHostPolicy
	tokenAwarePolicy, ok := s.policy.(*tokenAwareHostPolicy)
	if !ok {
		return ShardAwareRoutingInfo{}, fmt.Errorf("unsupported host policy type %T, must be tokenAwareHostPolicy", s.policy)
	}

	// get keyspace metadata
	md, err := s.KeyspaceMetadata(keyspace)
	if err != nil {
		return ShardAwareRoutingInfo{}, err
	}

	// get routing key from colums

	tableMd, ok := md.Tables[table]
	if !ok {
		return ShardAwareRoutingInfo{}, fmt.Errorf("table %v metadata not found", table)
	}

	var (
		pk      = tableMd.PartitionKey
		indexes = make([]int, len(pk))
		types   = make([]TypeInfo, len(pk))
	)
	for keyIndex, keyColumn := range pk {
		// set an indicator for checking if the mapping is missing
		indexes[keyIndex] = -1

		// find the column in the query info
		for argIndex, boundColumnName := range primaryKeyColumnNames {
			if keyColumn.Name == boundColumnName {
				// there may be many such bound columns, pick the first
				indexes[keyIndex] = argIndex
				types[keyIndex] = getCassandraTypeWithVersion(keyColumn.Type, s.logger, byte(s.connCfg.ProtoVersion))
				break
			}
		}

		if indexes[keyIndex] == -1 {
			// missing a routing key column mapping
			// no routing key
			return ShardAwareRoutingInfo{}, errors.New("missing a routing key column")
		}
	}

	// create routing key
	routingKey, err := createRoutingKey(&routingKeyInfo{
		indexes: indexes,
		types:   types,
	}, args)
	if err != nil {
		return ShardAwareRoutingInfo{}, err
	}

	// get token ring metadata
	cm := tokenAwarePolicy.getMetadataReadOnly()
	if cm == nil || cm.tokenRing == nil {
		return ShardAwareRoutingInfo{}, errors.New("can't get token ring metadata")
	}

	// get host by partition key
	host, token, _ := cm.tokenRing.GetHostForPartitionKey(routingKey)
	mmt, ok := token.(int64Token)
	if !ok { // check if that's murmur3 token
		return ShardAwareRoutingInfo{}, fmt.Errorf("unsupported token type %T, must be int64Token", token)
	}

	// get host connection pool
	pool, ok := s.pool.getPool(host)
	if !ok {
		return ShardAwareRoutingInfo{}, fmt.Errorf("can't get connection pool of host %s", host.Hostname())
	}

	// check that connection pool is scylla pool
	cp, ok := pool.connPicker.(*scyllaConnPicker)
	if !ok {
		return ShardAwareRoutingInfo{}, fmt.Errorf("unsupported connection picker type %T, must be scyllaConnPicker", pool.connPicker)
	}

	return ShardAwareRoutingInfo{
		RoutingKey: routingKey,      // routing key
		Host:       host,            // host by key
		Shard:      cp.shardOf(mmt), // calculate shard
	}, nil
}
```

**Comment by vikmik** [comment]
Did you benchmark your approach? For what it's worth, I did test my application and found that in my case it didn't help. ScyllaDB is so good at handling concurrent queries that I found no compelling reason to extend the driver code and have to maintain that. I suspect that ScyllaDB is less efficient at load balancing queries that can vary in size than it is at handling many many concurrent queries. That was 3 years ago though.

**Comment by moguchev** [comment]
It really depends on kind of load. ScyllaDB is really good at handling concurrent queries but when we have 1,5M/rps with 100-500 different keys (from different partitions) per one query on one insert or read, concurrent queries with single keys is not efficient.

We did several experiments and  found that ScyllaDB can insert big `BATCH`es efficiently if all keys in batch are corresponded to one host (so strategy is Host Aware). And `SELECT IN` queries is efficiently when it has less or equal 10 keys corresponded to one shard (so strategy is Shard Aware). That's why I wrote this extension API and uses in our application.

You should also understand that ScyllaDB is really good at parallelism, so it's important to have a threaded approach to handling queries in your application in order to ensure maximum utilization of ScyllaDB.

**Comment by mykaul** [comment]
@moguchev - how do you handle individual query failures?

**Comment by moguchev** [comment]
In insert queries we have a background retry queue, so we are hope that some failed queries will retried with success (of course we monitore such queries)

In read queries in real time we can nothing to do with some individual failed queries, so we degrade functionality and notify clients, that they can re-request some values. This is trade off. In some applications it cannot be done. We are lucky so we can afford this strategy.

**Comment by dkropachev** [comment]
i would suggest to close this issue in favor of https://github.com/scylladb/gocql/issues/200
