### ISSUE TITLE
Gocql driver does not recover after a node failover

### ISSUE THREAD

**Issue by noam-ma-ma** [scylladb/gocql#82]
Please answer these questions before submitting your issue. Thanks!

### What version of Scylla or Cassandra are you using?
Scylla Enterprise 2020.1.7

### What version of Gocql are you using?
`replace github.com/gocql/gocql => github.com/scylladb/gocql v0.0.0-20210425135552-909f2a77f46e`

### What version of Go are you using?
1.13

### What did you do?
1. Inserted some data to the Scylla.
2. Run a workload that reads a random partition key from the database with gocql client.
3. Restart 1 scylla node - the coordinator metrics starts to look odd - client still ok.
4. Restarted a second scylla node - the coordinator metrics are really bad, client still ok.
5. Restarted the third scylla node - the client returns error no hosts available.

### What did you expect to see?
That the gocql client realize that the restarted node(s) are back online, and direct traffic to them.

### What did you see instead?
After restarting scylla nodes, the driver does not send the requests, only after restarting the gocql application.
When 3 nodes have been restarted, the client gets `no hosts available` errors. 

---

After a node failover, the client does not direct traffic to the restarted node, but instead it directs the traffic to the other 2 nodes.
Following that, we restarted another node, which caused the client to direct all the traffic to a single coordinator node, even that all of the nodes are online.
Meanwhile In the cluster metrics in Grafana - the other nodes does accept requests, but only from a single coordinator node (the node that didn't restarted).
When we restarted the last node, all of the client requests failed with `no hosts available errors`.
To fix this situation we restarted the client.

I attached a trace of the gocql client before the restart, and after the restart, and the go client code (+go.mod) that run this this workload here in this: B0004DAC-92E9-46EB-A366-F8F044DC9E12

Thanks!

**Comment by mmatczuk** [comment]
`no hosts available` is a longstanding issue in the upstream gocql.
Is there any progress on that @martin-sucha.
Maybe https://github.com/gocql/gocql/commit/312a614907c8d2e19f6b14aff16015436cb78423?

**Comment by gcarmin** [comment]
@mmatczuk  - the main issue is that when a node goes down, the driver doesn't connect to it after the node goes back up.

**Comment by martin-sucha** [comment]
Indeed https://github.com/gocql/gocql/commit/312a614907c8d2e19f6b14aff16015436cb78423 fixes regression that was introduced in https://github.com/gocql/gocql/pull/1369

scylladb/gocql has https://github.com/gocql/gocql/pull/1369 but not https://github.com/gocql/gocql/commit/312a614907c8d2e19f6b14aff16015436cb78423. The latter should fix the problem with reconnecting (to the extent that it should work as before the regression).

**Comment by gcarmin** [comment]
@mmatczuk @martin-sucha  - do we have any time-line to get this fix into scylladb/gocql?

**Comment by martin-sucha** [comment]
That is entirely up to Scylla folks when they merge changes from upstream to this fork, I don't have write access to this repo.

@mmatczuk I've just merged https://github.com/gocql/gocql/pull/1571 upstream that fixes another regression in Session.close (introduced in https://github.com/gocql/gocql/commit/312a614907c8d2e19f6b14aff16015436cb78423), so when merging please include these changes as well.

**Comment by noam-ma-ma** [comment]
@mmatczuk Is it possible to pull the latest gocql drivers?
If it's a simple fix we really need this for our production workload.

Thanks!

**Comment by mmatczuk** [comment]
Done.

**Comment by noam-ma-ma** [comment]
Thanks @mmatczuk 😄 , we'll try the new version ASAP
